<?php 
	
	if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array (
			'key' => 'group_5644619e12701',
			'title' => 'Kioskplatser',
			'fields' => array (
				array (
					'key' => 'field_564463db4e449',
					'label' => '',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'message' => 'Här listas platserna för samtliga kiosker som finns i installationen. Varje kiosk uppdaterar automatiskt sin plats vid första besöket. Om en kiosk skulle hamna fel på kartan, kan du ändra den här. Tar du bort en kiosk, kommer den att dyka upp här igen när den används första gången.

		Samtliga kiosker kräver att en position finns lagrad för att plotta ut en vägbeskrivning till målet.',
					'new_lines' => 'wpautop',
					'esc_html' => 1,
				),
				array (
					'key' => 'field_5644646632d1a',
					'label' => 'Kiosker',
					'name' => 'kiosk_repeater',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Lägg till kiosk',
					'sub_fields' => array (
						array (
							'key' => 'field_564499deb00c3',
							'label' => 'Kiosknamn',
							'name' => 'kiosk_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_564461a9025b6',
							'label' => 'Kiosk IP',
							'name' => 'kiosk_ip',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_564462fff65ec',
							'label' => 'Kiosk Latitude',
							'name' => 'kiosk_lat',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5644635c37050',
							'label' => 'Kiosk Longitude',
							'name' => 'kiosk_long',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'kiosk-places',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		));

	endif;
	