<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_563b250684b8b',
    'title' => 'Screensaver settings',
    'fields' => array (
        array (
            'key' => 'field_564c680c84cea',
            'label' => 'Lead rubrik',
            'name' => 'screensaver-lead-title',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Hallå där',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_564c682884ceb',
            'label' => 'Lead caption',
            'name' => 'screensaver-lead-caption',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Hitta saker att göra i Helsingborg stad',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_563b4e09a647c',
            'label' => 'Media',
            'name' => 'screensaver-media',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => 'Lägg till media',
            'min' => '',
            'max' => '',
            'layouts' => array (
                array (
                    'key' => '563b4e15498ab',
                    'name' => 'screensaver-instagram',
                    'label' => 'Instagram hashtag',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_563b4e18a647d',
                            'label' => 'Hashtag',
                            'name' => 'screensaver-hashtag',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '33.333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_564ae59c728c8',
                            'label' => 'Aktiv tid',
                            'name' => 'screensaver-slide-timeout',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '33.333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 7000,
                            'placeholder' => '',
                            'prepend' => 'Visa i',
                            'append' => 'millisekunder',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_564aec91d29f3',
                            'label' => 'Visa "Hallåa"',
                            'name' => 'screensaver-hide-cta',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '33.333',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Visa',
                            'default_value' => 1,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '564b38d15ccb0',
                    'name' => 'screensaver-twitter',
                    'label' => 'Twitter hashtag',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_564b38d15ccb1',
                            'label' => 'Hashtag',
                            'name' => 'screensaver-hashtag',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '33.333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_564b38d15ccb2',
                            'label' => 'Aktiv tid',
                            'name' => 'screensaver-slide-timeout',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '33.333',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 7000,
                            'placeholder' => '',
                            'prepend' => 'Visa i',
                            'append' => 'millisekunder',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_564b38d15ccb3',
                            'label' => 'Visa "Hallåa"',
                            'name' => 'screensaver-hide-cta',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '33.333',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Visa',
                            'default_value' => 1,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '563b4e58a647e',
                    'name' => 'screensaver-gallery',
                    'label' => 'Galleri',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_563b4e69a647f',
                            'label' => 'Galleri',
                            'name' => 'screensaver-gallery-images',
                            'type' => 'gallery',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => '',
                            'max' => '',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array (
                            'key' => 'field_564ae605728c9',
                            'label' => 'Aktiv tid',
                            'name' => 'screensaver-slide-timeout',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 7000,
                            'placeholder' => '',
                            'prepend' => 'Visa i',
                            'append' => 'millisekunder',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_564aeccbd29f4',
                            'label' => 'Visa "Hallåa"',
                            'name' => 'screensaver-hide-cta',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Visa',
                            'default_value' => 1,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '564ae077efa84',
                    'name' => 'screensaver-poster',
                    'label' => 'Affisch',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_564ae085efa85',
                            'label' => 'Bild',
                            'name' => 'screensaver-poster-image',
                            'type' => 'image',
                            'instructions' => 'OBS! Bilden måste vara i storleken 1080x1920 pixlar.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => 1080,
                            'min_height' => 1920,
                            'min_size' => '',
                            'max_width' => 1080,
                            'max_height' => 1920,
                            'max_size' => '',
                            'mime_types' => 'jpg, png',
                        ),
                        array (
                            'key' => 'field_564ae621728ca',
                            'label' => 'Aktiv tid',
                            'name' => 'screensaver-slide-timeout',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 7000,
                            'placeholder' => '',
                            'prepend' => 'Visa i',
                            'append' => 'millisekunder',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_564aecd8d29f5',
                            'label' => 'Visa "Hallåa"',
                            'name' => 'screensaver-hide-cta',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Visa',
                            'default_value' => 1,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '564aef5f3288b',
                    'name' => 'screensaver-events',
                    'label' => 'Evenemang',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_564af6250a004',
                            'label' => 'Rubrik',
                            'name' => 'screensaver-events-title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_564aef763288c',
                            'label' => 'Antal evenemang att visa',
                            'name' => 'screensaver-events-show',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 5,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_564aefa83288d',
                            'label' => 'Aktiv tid',
                            'name' => 'screensaver-slide-timeout',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 7000,
                            'placeholder' => '',
                            'prepend' => 'Visa i',
                            'append' => 'millisekunder',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_564af2e520426',
                            'label' => 'Visa "Hallåa"',
                            'name' => 'screensaver-hide-cta',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Visa',
                            'default_value' => 1,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'screensaver',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

endif;