<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_564c3b2c2539d',
    'title' => 'Takeover',
    'fields' => array (
        array (
            'key' => 'field_564c3b3388aa5',
            'label' => 'Takeovers',
            'name' => 'takeovers',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => '',
            'max' => '',
            'layout' => 'block',
            'button_label' => 'Lägg till takeover',
            'sub_fields' => array (
                array (
                    'key' => 'field_564c4b7ac16dc',
                    'label' => 'ID',
                    'name' => 'takeover_id',
                    'type' => 'unique_id',
                    'instructions' => 'Skapas automatiskt',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '33.333%',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array (
                    'key' => 'field_564c3c4088aa8',
                    'label' => 'Datum för visning',
                    'name' => 'takeover_date',
                    'type' => 'date_picker',
                    'instructions' => 'Datum i format YYYY-MM-DD',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '33.333%',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                ),
                array (
                    'key' => 'field_564c3c8688aa9',
                    'label' => 'Tid för visning',
                    'name' => 'takeover_time',
                    'type' => 'text',
                    'instructions' => 'Ange klockslag i formatet HH:MM',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '33.333%',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'HH:MM',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_564c3b4988aa6',
                    'label' => 'Media (film eller bild)',
                    'name' => 'takeover_media',
                    'type' => 'file',
                    'instructions' => 'Välj en bild eller film som ska visas. Storleken bör vara fixerad till 1080x1920 pixlar. Format för video: mp4 eller webm.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => 'mp4, webm, jpg, png',
                ),
                array (
                    'key' => 'field_564c3be588aa7',
                    'label' => 'Meddelande',
                    'name' => 'takeover_message',
                    'type' => 'textarea',
                    'instructions' => 'Text som visas under hela uppspelningstiden, lägger sig i nedre kanten ovanpå video/bild.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => 'wpautop',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_564c4f8f07bce',
                    'label' => 'Visa i antal millisekunder (gäller endast för bilder)',
                    'name' => 'takeover_timeout',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 3000,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'millisekunder',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'takeover',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

endif;